machine:
  python:
    version: 3.6.1

dependencies:
  post:
    - pip install -U -r requirements.txt
    - pip install git+https://github.com/fancycode/pylzma.git

test:
  override:
    - python setup.py unittests