language: python
python:
  - {{Python34}}
  - {{Python35}}
  - {{Python27}}
  - conda|{{Anaconda35}}
  - conda|{{Anaconda27}}
  - {{WinPython35}}
virtualenv:
  - path: {{root_path}}/_virtualenv/{{project_name}}
install:
  - pip install -r requirements.txt
script:
  - python setup.py unittests
  - python setup.py unittests [LONG]
  - python setup.py unittests [SKIP]
documentation:
  - if [ ${PYTHON} == "{{Python35}}" ] then
    python setup.py build_sphinx
    fi
