dist: xenial
sudo: true
language: python
matrix:
  include:
  - python: 3.7.3
    name: "Py.3.7.3-Sph.2.1"
    env: sphinxconstraint=">=2.1"
install: 
    - pip install -r requirements.txt
    - npm install
    - pip install sphinx$sphinxconstraint
    - pip install tkinterquickhelper --no-deps
    - export PYTHONPATH=src
script:
    - python setup.py unittests
