dist: trusty
language: python
python:
    - "3.5"
    - "3.6"
install: 
    - pip install -r requirements.txt
    - pip install git+https://github.com/fancycode/pylzma.git
    - pip install git+https://github.com/sdpython/sphinxcontrib-images.git
script:
    - python setup.py unittests
