dist: focal
sudo: true
language: python
matrix:
  include:
  - python: 3.9.1
    name: "Py.3.9.1-Sph.2.3"
    env: sphinxconstraint=">=2.3"
install: 
    - pip install -r requirements.txt
    - npm install
    - pip install sphinx$sphinxconstraint
    - pip install tkinterquickhelper --no-deps
    - export PYTHONPATH=src
script:
    - python setup.py unittests
