dist: trusty
language: python
python:
    - "3.6"
    - "3.7"
install: 
    - pip install -r requirements.txt
    - pip install git+https://github.com/fancycode/pylzma.git --upgrade --no-deps
    - pip install git+https://github.com/sdpython/sphinxcontrib-images.git --upgrade --no-deps
    - npm install
script:
    - python setup.py unittests
