environment:

  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    WITH_COMPILER: "cmd /E:ON /V:ON /C .\\appveyor\\run_with_compiler.cmd"

  matrix:

    - PYTHON: "C:\\Python37-x64"
      PYTHON_VERSION: "3.7.x"
      PYTHON_ARCH: "64"

cache:
  - c:\miktex -> .\miktex-install.bat

install:
    - set "PATH=%PATH%;c:\miktex\miktex\bin"
    - if not exist c:\miktex\miktex\bin\pdflatex.exe .\miktex-install.bat    
    # Python
    - "%PYTHON%\\python -m pip install --upgrade pip"
    - "%PYTHON%\\Scripts\\pip install pymyinstall"
    - "%PYTHON%\\Scripts\\pymy_install3 --set=pyquickhelper"
    - "%PYTHON%\\Scripts\\pymy_install3 pylzma"
    - "%PYTHON%\\Scripts\\pip install cryptography pycryptodomex"
    - "%PYTHON%\\Scripts\\pip install backports.shutil-get-terminal-size"
    - "%PYTHON%\\Scripts\\pip install https://github.com/ipython-contrib/jupyter_contrib_nbextensions/tarball/master"
    - "%PYTHON%\\Scripts\\pip install -r requirements.txt"
    - "dir %PYTHON%\\Scripts"
    - "%PYTHON%\\Scripts\\jupyter-nbextension enable --py --sys-prefix widgetsnbextension"
    - "%PYTHON%\\Scripts\\pymy_install3 --task=tool --source=zip graphviz"
    - "%PYTHON%\\python -c \"from pymyinstall.fix import fix_win32ctypes_core_cffi__advapi32_py;fix_win32ctypes_core_cffi__advapi32_py(fLOG=print)\""
    - "%PYTHON%\\Scripts\\pip install tkinterquickhelper --no-deps"
    - set PYTHONPATH=src

build: off

before_test:
  - cinst pandoc
  - ps: $env:Path += ";C:\Program Files (x86)\Pandoc\"
  - pandoc -v
  - cinst imagemagick

test_script:
  - "%PYTHON%\\python -u setup.py build_script"
  - "%PYTHON%\\python -u setup.py unittests"
  
after_test:
  - "%PYTHON%\\python -u setup.py bdist_wheel"

artifacts:
  - path: dist
    name: pyquickhelper

cache:
  # Use the appveyor cache to avoid re-downloading large archives such
  # the MKL numpy and scipy wheels mirrored on a rackspace cloud
  # container, speed up the appveyor jobs and reduce bandwidth.
  # Tips taken from scikit-learn.
  - '%APPDATA%\pip\Cache'
