pool:
  vmImage: 'Ubuntu 16.04'

steps:
- script: pip install -r requirements.txt
  displayName: 'Install dependencies'
- script: python setup.py unittest
  displayName: 'Runs unit tests'
- script: python setup.py bdist_wheel
  displayName: 'Build package'
- script: python setup.py build_sphinx
  displayName: 'Builds documentation'
