version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
    
    working_directory: ~/repo
    
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          - v1-dependencies-

      - run:
          name: pandoc latex
          command: |
                    sudo aptitude update -y
                    sudo aptitude install -y texlive-xetex fonts-ipafont bc jq
                    wget https://github.com/jgm/pandoc/releases/download/1.19.2.1/pandoc-1.19.2.1-1-amd64.deb
                    sudo dpkg -i pandoc-1.19.2.1-1-amd64.deb
          
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install git+https://github.com/fancycode/pylzma.git

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
        
      - run:
          name: documentation
          command: |
            . venv/bin/activate
            python setup.py build_sphinx

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python setup.py unittests

      - run:
          name: wheel
          command: |
            . venv/bin/activate
            python setup.py bdist_wheel
            cp dist/*.whl test-reports

      - store_artifacts:
          path: test-reports
          destination: test-reports